import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../components/Layout';
import { Animal } from '../database/animals';
import queryGraphql from '../shared/query-graphql';
import styles from '../styles/Home.module.css';

type Props = {
  animals: Animal[];
};

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>GraphQL Example Fall 2022 Vienna Austria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className={styles.title}>Home</h1>
        <div className={styles.grid}>
          {props.animals.map((animal) => {
            return (
              <Link
                key={animal.id}
                className={styles.card}
                href={`/${animal.id}`}
              >
                <Image
                  src={`/images/${animal.id}-${animal.name.toLowerCase()}.jpeg`}
                  alt={animal.name}
                  width={200}
                  height={200}
                />
                <div>
                  <h2>{animal.name}</h2>
                </div>
              </Link>
            );
          })}
        </div>
      </Layout>
    </>
  );
}

export async function getServerSideProps() {
  const { animals } = await queryGraphql(`
query {
    animals {
    id
    name
  }
}
`);

  return {
    props: {
      animals,
    },
  };
}
